# Generated by Django 5.2.3 on 2025-07-25 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="telegram_code",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Telegram code"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="telegram_id",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Telegram"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="telegram_verifyed",
            field=models.BooleanField(
                default=False, verbose_name="Подтверждение Telegram ID"
            ),
        ),
    ]
