# Generated by Django 5.2.3 on 2025-07-25 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_telegram_code_user_telegram_id_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="telegram_verifyed",
            new_name="telegram_verified",
        ),
    ]
