# Generated by Django 5.2.3 on 2025-07-25 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_rename_telegram_verifyed_user_telegram_verified"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="telegram_verified",
            new_name="is_telegram_verified",
        ),
    ]
