# Generated by Django 5.2.3 on 2025-07-25 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_rename_telegram_verified_user_is_telegram_verified"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="telegram_chat_id",
            field=models.CharField(
                blank=True, null=True, verbose_name="Telegram chat id"
            ),
        ),
    ]
