events {
    worker_connections 1024;
}

http {
    upstream django {
        server web:8000;  # Имя сервиса из docker-compose
    }

    server {
        root /app/;

        location / {
            try_files $uri $uri/ /index.html;
            proxy_read_timeout 1800;
            proxy_connect_timeout 1800;
            proxy_send_timeout 1800;
            send_timeout 1800;
        }

        location /admin {
            proxy_pass http://host.docker.internal:8080;
        }

        location /tracker {
            rewrite ^/tracker/(.*) /$1 break;
            proxy_pass http://host.docker.internal:8080;
            proxy_read_timeout 1800;
            proxy_connect_timeout 1800;
            proxy_send_timeout 1800;
            send_timeout 1800;
        }
    }

    server {
        listen 80;
        server_name 51.250.17.3;

        location / {
            proxy_pass http://django;  # Прокси на бэкенд
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}