upstream django {
    server web:8000;  # Имя сервиса из docker-compose.yml
}

server {
    root /var/projects/healthy-habits-tracker/;

    location / {
        try_files $uri $uri/ /index.html;
        proxy_read_timeout 1800;
        proxy_connect_timeout 1800;
        proxy_send_timeout 1800;
        send_timeout 1800;
    }

    listen 80;
    server_name 51.250.17.3;  # Ваш домен или IP

    location /admin {
        proxy_pass http://host.docker.internal:8080;
    }

    location /static/admin {
        proxy_pass http://host.docker.internal:8080;
    }

    location /static/ {
        proxy_pass http://host.docker.internal:8080;
    }

    location /media/ {
        proxy_pass http://host.docker.internal:8080;
    }

    # Основное приложение
    location / {
        rewrite ^/tracker/(.*) /$1 break;
        proxy_pass http://host.docker.internal:8080;
        proxy_read_timeout 1800;
        proxy_connect_timeout 1800;
        proxy_send_timeout 1800;
        send_timeout 1800;
    }

    server {
        listen 8080;
        server_name 51.250.17.3;
        location / {
            proxy_pass http://host.docker.internal:8000;
            proxy_set_header Host $host;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_redirect ~*http://[^/]+(/.*)$ $1;
            proxy_read_timeout 1800;
            proxy_connect_timeout 1800;
            proxy_send_timeout 1800;
            send_timeout 1800;
        }
    }
}