# Generated by Django 5.2.3 on 2025-07-24 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Habit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("place", models.CharField(blank=True, max_length=100, null=True)),
                ("time", models.TimeField(auto_now_add=True)),
                ("action", models.CharField(blank=True, max_length=100, null=True)),
                ("is_healthy", models.BooleanField(default=True)),
                ("period", models.IntegerField(default=7)),
                ("reward", models.CharField(blank=True, max_length=100, null=True)),
                ("action_time", models.IntegerField(default=120)),
                ("is_public", models.BooleanField(default=False)),
                (
                    "nice_habit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tracker.habit",
                    ),
                ),
            ],
            options={
                "verbose_name": "Привычка",
                "verbose_name_plural": "Привычки",
                "ordering": ["id", "title", "owner", "place"],
            },
        ),
    ]
