# Generated by Django 5.2.3 on 2025-07-21 16:54

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="nicehabit",
            name="is_healthy",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="HealthyHabit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("place", models.CharField(blank=True, max_length=100, null=True)),
                ("time", models.DateTimeField(auto_now_add=True)),
                ("action", models.CharField(blank=True, max_length=100, null=True)),
                ("is_healthy", models.BooleanField(default=True)),
                (
                    "period",
                    models.CharField(
                        blank=True, default="1 week", max_length=10, null=True
                    ),
                ),
                ("reward", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "action_time",
                    models.TimeField(default=datetime.timedelta(seconds=120)),
                ),
                ("is_public", models.BooleanField(default=False)),
                (
                    "nice_habit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tracker.nicehabit",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Привычка",
                "verbose_name_plural": "Привычки",
                "ordering": ["title", "owner", "place"],
            },
        ),
        migrations.DeleteModel(
            name="Habit",
        ),
    ]
