# Generated by Django 5.2.3 on 2025-07-25 14:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="habit",
            name="last_action",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 7, 25, 14, 7, 22, 102279, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
