# Generated by Django 5.2.3 on 2025-07-25 15:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0003_habit_last_action"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="last_action",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 7, 25, 15, 12, 38, 635147, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="time",
            field=models.TimeField(
                default=datetime.datetime(
                    2025, 7, 25, 15, 12, 38, 633068, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
