# Generated by Django 5.2.3 on 2025-07-21 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0003_nicehabit_is_healthy_healthyhabit_delete_habit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="healthyhabit",
            name="reward",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
