# Generated by Django 5.2.3 on 2025-08-16 07:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0004_alter_habit_last_action_alter_habit_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="last_action",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="habit",
            name="time",
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
